"""
앱 트렌드 트래커 — 모니터링 대상 앱 설정
각 앱의 Play Store ID, App Store ID, 도메인 분류, 뉴스 검색 키워드 등을 관리합니다.
"""

APPS = {
    # ═══ 1. 전통 금융사 (은행·카드사) ═══
    "toss_bank": {
        "name": "토스",
        "color": "#3182f6",
        "initial": "T",
        "domain": "fintech",
        "domainLabel": "핀테크",
        "play_id": "viva.republica.toss",
        "itunes_id": "839333328",
        "news_keywords": ["토스 앱 업데이트", "토스뱅크 신기능", "토스 이벤트"],
        "src": "https://toss.im",
        "channels": ["App Store 업데이트 노트", "Play Store 업데이트 노트", "토스 공식 블로그", "앱 내 공지·이벤트 배너"],
    },
    "kakao_bank": {
        "name": "카카오뱅크",
        "color": "#FFCD00",
        "initial": "K",
        "domain": "fintech",
        "domainLabel": "핀테크",
        "play_id": "com.kakaobank.channel",
        "itunes_id": "1258016944",
        "news_keywords": ["카카오뱅크 업데이트", "카카오뱅크 신기능", "카카오뱅크 이벤트"],
        "src": "https://www.kakaobank.com",
        "channels": ["App Store 업데이트 노트", "Play Store 업데이트 노트", "카카오뱅크 뉴스룸", "앱 내 이벤트 배너"],
    },
    "kb_bank": {
        "name": "KB국민은행",
        "color": "#b07f36",
        "initial": "KB",
        "domain": "traditional",
        "domainLabel": "전통금융",
        "play_id": "com.kbstar.kbbank",
        "itunes_id": "373742138",
        "news_keywords": ["KB스타뱅킹 업데이트", "KB국민은행 신기능", "KB국민은행 이벤트"],
        "src": "https://www.kbstar.com",
        "channels": ["App Store 업데이트 노트", "Play Store 업데이트 노트", "KB 보도자료", "공식 블로그"],
    },
    "shinhan_bank": {
        "name": "신한은행",
        "color": "#0046ff",
        "initial": "SH",
        "domain": "traditional",
        "domainLabel": "전통금융",
        "play_id": "com.shinhan.sbanking",
        "itunes_id": "357484932",
        "news_keywords": ["신한SOL뱅크 업데이트", "신한은행 신기능", "신한은행 이벤트"],
        "src": "https://www.shinhan.com",
        "channels": ["App Store 업데이트 노트", "Play Store 업데이트 노트", "신한 보도자료", "공식 뉴스룸"],
    },
    "woori_bank": {
        "name": "우리은행",
        "color": "#0072bc",
        "initial": "W",
        "domain": "traditional",
        "domainLabel": "전통금융",
        "play_id": "com.wooribank.smart.npib",
        "itunes_id": "1470181651",
        "news_keywords": ["우리WON뱅킹 업데이트", "우리은행 신기능"],
        "src": "https://www.wooribank.com",
        "channels": ["App Store 업데이트 노트", "Play Store 업데이트 노트", "우리은행 보도자료"],
    },
    "hana_bank": {
        "name": "하나은행",
        "color": "#009490",
        "initial": "H",
        "domain": "traditional",
        "domainLabel": "전통금융",
        "play_id": "com.kebhana.hanapush",
        "itunes_id": "1574898498",
        "news_keywords": ["하나원큐 업데이트", "하나은행 신기능", "하나은행 이벤트"],
        "src": "https://www.kebhana.com",
        "channels": ["App Store 업데이트 노트", "Play Store 업데이트 노트", "하나은행 보도자료", "공식 블로그"],
    },
    "nh_bank": {
        "name": "NH농협은행",
        "color": "#00703c",
        "initial": "NH",
        "domain": "traditional",
        "domainLabel": "전통금융",
        "play_id": "nh.smart.banking",
        "itunes_id": "751744939",
        "news_keywords": ["NH올원뱅크 업데이트", "NH농협은행 신기능"],
        "src": "https://www.nhbank.com",
        "channels": ["App Store 업데이트 노트", "Play Store 업데이트 노트", "NH 보도자료"],
    },
    "ibk_bank": {
        "name": "IBK기업은행",
        "color": "#005baa",
        "initial": "IBK",
        "domain": "traditional",
        "domainLabel": "전통금융",
        "play_id": "com.ibk.neobanking",
        "itunes_id": "1507543606",
        "news_keywords": ["IBK i-ONE뱅크 업데이트", "IBK기업은행 신기능"],
        "src": "https://www.ibk.co.kr",
        "channels": ["App Store 업데이트 노트", "Play Store 업데이트 노트", "IBK 보도자료"],
    },
    "k_bank": {
        "name": "케이뱅크",
        "color": "#ffb500",
        "initial": "K",
        "domain": "fintech",
        "domainLabel": "핀테크",
        "play_id": "com.kbank.banking",
        "itunes_id": "1178872627",
        "news_keywords": ["케이뱅크 업데이트", "케이뱅크 신기능", "케이뱅크 이벤트"],
        "src": "https://www.kbanknow.com",
        "channels": ["App Store 업데이트 노트", "Play Store 업데이트 노트", "케이뱅크 공식 블로그"],
    },

    # ═══ 2. 빅테크·결제/핀테크 ═══
    "toss_fin": {
        "name": "토스",
        "color": "#3182f6",
        "initial": "T",
        "domain": "fintech",
        "domainLabel": "핀테크",
        "play_id": "viva.republica.toss",
        "itunes_id": "839333328",
        "news_keywords": ["토스 간편결제", "토스 투자", "토스 보험", "토스 마이데이터"],
        "src": "https://toss.im",
        "channels": ["App Store 업데이트 노트", "Play Store 업데이트 노트", "토스 블로그·공지", "공식 SNS (X·인스타그램)"],
    },
    "kakao_pay": {
        "name": "카카오페이",
        "color": "#FFCD00",
        "initial": "KP",
        "domain": "fintech",
        "domainLabel": "핀테크",
        "play_id": "com.kakaopay.app",
        "itunes_id": "1464496236",
        "news_keywords": ["카카오페이 업데이트", "카카오페이 신기능", "카카오페이 이벤트"],
        "src": "https://www.kakaopay.com",
        "channels": ["App Store 업데이트 노트", "Play Store 업데이트 노트", "카카오페이 스토리·공지", "이벤트·쿠폰 페이지"],
    },
    "naver_pay": {
        "name": "네이버페이",
        "color": "#03c75a",
        "initial": "N",
        "domain": "fintech",
        "domainLabel": "핀테크",
        "play_id": "com.naverfin.payapp",
        "itunes_id": "1187508712",
        "news_keywords": ["네이버페이 업데이트", "네이버파이낸셜 신기능", "네이버페이 이벤트"],
        "src": "https://www.naverfincorp.com",
        "channels": ["App Store 업데이트 노트", "Play Store 업데이트 노트", "네이버파이낸셜 공지", "네이버페이 이벤트 페이지"],
    },
    "payco": {
        "name": "페이코",
        "color": "#e5243b",
        "initial": "P",
        "domain": "fintech",
        "domainLabel": "핀테크",
        "play_id": "com.nhnent.payapp",
        "itunes_id": "924292102",
        "news_keywords": ["페이코 업데이트", "페이코 신기능"],
        "src": "https://www.payco.com",
        "channels": ["App Store 업데이트 노트", "Play Store 업데이트 노트", "NHN페이코 공지"],
    },
    "samsung_pay": {
        "name": "삼성페이",
        "color": "#1428a0",
        "initial": "SP",
        "domain": "fintech",
        "domainLabel": "핀테크",
        "play_id": "com.samsung.android.spay",
        "itunes_id": None,  # Samsung Pay는 iOS 없음
        "news_keywords": ["삼성페이 업데이트", "삼성페이 신기능"],
        "src": "https://www.samsung.com",
        "channels": ["Play Store 업데이트 노트", "삼성 뉴스룸"],
    },

    # ═══ 3. 이커머스 ═══
    "coupang": {
        "name": "쿠팡",
        "color": "#e52528",
        "initial": "C",
        "domain": "commerce",
        "domainLabel": "이커머스",
        "play_id": "com.coupang.mobile",
        "itunes_id": "454434967",
        "news_keywords": ["쿠팡 앱 업데이트", "쿠팡 신기능", "쿠팡 로켓와우 이벤트"],
        "src": "https://www.coupang.com",
        "channels": ["App Store 업데이트 노트", "Play Store 업데이트 노트", "쿠팡 뉴스룸", "이벤트·혜택 페이지"],
    },
    "naver_shop": {
        "name": "네이버 쇼핑",
        "color": "#03c75a",
        "initial": "N",
        "domain": "commerce",
        "domainLabel": "이커머스",
        "play_id": "com.nhn.android.search",
        "itunes_id": "393499958",
        "news_keywords": ["네이버쇼핑 업데이트", "네이버쇼핑 신기능", "네이버쇼핑 이벤트"],
        "src": "https://shopping.naver.com",
        "channels": ["Play Store 업데이트 노트", "네이버 이벤트 모아보기", "네이버 쇼핑 공지"],
    },
    "st11": {
        "name": "11번가",
        "color": "#ff0038",
        "initial": "11",
        "domain": "commerce",
        "domainLabel": "이커머스",
        "play_id": "com.elevenst.deals",
        "itunes_id": "400498498",
        "news_keywords": ["11번가 앱 업데이트", "11번가 신기능", "11번가 십일절"],
        "src": "https://www.11st.co.kr",
        "channels": ["App Store 업데이트 노트", "Play Store 업데이트 노트", "11번가 이벤트·혜택·쿠폰 메뉴"],
    },
    "gmarket": {
        "name": "G마켓",
        "color": "#4daf51",
        "initial": "G",
        "domain": "commerce",
        "domainLabel": "이커머스",
        "play_id": "com.ebay.kr.gmarket",
        "itunes_id": "382989498",
        "news_keywords": ["G마켓 앱 업데이트", "G마켓 신기능"],
        "src": "https://www.gmarket.co.kr",
        "channels": ["App Store 업데이트 노트", "Play Store 업데이트 노트", "G마켓 이벤트 페이지"],
    },
    "ssg": {
        "name": "SSG닷컴",
        "color": "#ff5452",
        "initial": "SS",
        "domain": "commerce",
        "domainLabel": "이커머스",
        "play_id": "com.shinsegae.mobile.ssg",
        "itunes_id": "490498070",
        "news_keywords": ["SSG닷컴 업데이트", "SSG닷컴 쓱데이", "SSG닷컴 이벤트"],
        "src": "https://www.ssg.com",
        "channels": ["App Store 업데이트 노트", "Play Store 업데이트 노트", "SSG 이벤트·혜택 메뉴"],
    },
    "wemakeprice": {
        "name": "위메프",
        "color": "#f14f5c",
        "initial": "WM",
        "domain": "commerce",
        "domainLabel": "이커머스",
        "play_id": "com.wemakeprice",
        "itunes_id": "422399498",
        "news_keywords": ["위메프 앱 업데이트", "위메프 이벤트"],
        "src": "https://www.wemakeprice.com",
        "channels": ["App Store 업데이트 노트", "Play Store 업데이트 노트", "위메프 이벤트 페이지"],
    },

    # ═══ 4. 버티컬 커머스 ═══
    "musinsa": {
        "name": "무신사",
        "color": "#111111",
        "initial": "M",
        "domain": "vertical",
        "domainLabel": "버티컬",
        "play_id": "com.musinsa.store",
        "itunes_id": "996877138",
        "news_keywords": ["무신사 앱 업데이트", "무신사 신기능", "무신사 콜라보"],
        "src": "https://www.musinsa.com",
        "channels": ["App Store 업데이트 노트", "Play Store 업데이트 노트", "무신사 매거진·블로그", "앱 내 기획전 영역"],
    },
    "cm29": {
        "name": "29CM",
        "color": "#111111",
        "initial": "29",
        "domain": "vertical",
        "domainLabel": "버티컬",
        "play_id": "com.the29cm.app29cm",
        "itunes_id": "1239018498",
        "news_keywords": ["29CM 앱 업데이트", "29CM 신기능", "29CM 기획전"],
        "src": "https://www.29cm.co.kr",
        "channels": ["App Store 업데이트 노트", "Play Store 업데이트 노트", "29CM 공식 뉴스레터"],
    },
    "kurly": {
        "name": "컬리",
        "color": "#5f0080",
        "initial": "K",
        "domain": "vertical",
        "domainLabel": "버티컬",
        "play_id": "com.dbs.kurly.m2",
        "itunes_id": "1048872498",
        "news_keywords": ["컬리 앱 업데이트", "마켓컬리 신기능", "컬리 기획전"],
        "src": "https://www.kurly.com",
        "channels": ["App Store 업데이트 노트", "Play Store 업데이트 노트", "컬리 공식 블로그", "앱 내 특가·기획전 영역"],
    },
    "ohouse": {
        "name": "오늘의집",
        "color": "#35c5f0",
        "initial": "O",
        "domain": "vertical",
        "domainLabel": "버티컬",
        "play_id": "com.bucketplace",
        "itunes_id": "1077498849",
        "news_keywords": ["오늘의집 앱 업데이트", "오늘의집 신기능", "오늘의집 이벤트"],
        "src": "https://ohou.se",
        "channels": ["App Store 업데이트 노트", "Play Store 업데이트 노트", "오늘의집 공식 블로그·뉴스레터"],
    },
}

# 데이터 보관 정책
DATA_POLICY = {
    "features_retention_months": 6,
    "marketing_retention_months": 3,
    "max_items": 2000,
    "auto_archive": True,
}
